export type ColorScheme = 'purple' | 'blue' | 'orange' | 'teal' | 'yellow' | 'maroon';

export const colorMap = {
    purple: {
        // Core colors
        primary: {
            from: 'from-deep-purple-500',
            to: 'to-deep-purple-700',
            hoverFrom: 'hover:from-deep-purple-600',
            hoverTo: 'hover:to-deep-purple-800',
        },
        // Component specific
        trigger: "border-deep-purple-300 focus:ring-deep-purple-500 focus:border-deep-purple-500",
        icon: "text-deep-purple-500",
        label: "text-deep-purple-800",
        topLine: "from-deep-purple-400 to-deep-purple-600",
        iconBg: "from-deep-purple-100 to-deep-purple-200",
        border: "border-deep-purple-100",
        checked: "data-[state=checked]:bg-deep-purple-600",
        thumb: "data-[state=checked]:bg-deep-purple-100",
        focus: "focus-visible:ring-deep-purple-500",
        // Tabs
        active: "bg-gradient-to-r from-deep-purple-500 to-deep-purple-700 text-white shadow-md",
        inactive: "text-deep-purple-600 hover:bg-deep-purple-50 border border-deep-purple-200",
        pills: "text-deep-purple-600 hover:bg-deep-purple-100 data-[state=active]:bg-gradient-to-r data-[state=active]:from-deep-purple-500 data-[state=active]:to-deep-purple-700 data-[state=active]:text-white",
        underline: "border-b-2 border-transparent hover:border-deep-purple-300 data-[state=active]:border-deep-purple-500 text-deep-purple-600",
        // Cards & Inputs
        cardBorder: "border-deep-purple-200",
        cardSelected: "border-deep-purple-500 bg-deep-purple-50",
        cardText: "text-deep-purple-700",
        cardHover: "hover:border-deep-purple-300",
        // For AnswerSelect and DetermineValueInput
        title: "text-deep-purple-800",
        hover: "hover:border-deep-purple-300",
        selected: "border-deep-purple-500 bg-deep-purple-50",
        text: "text-deep-purple-700",
        // Button specific
        button: {
            primary: "bg-gradient-to-r from-deep-purple-500 to-deep-purple-700 text-white hover:from-deep-purple-600 hover:to-deep-purple-800",
            secondary: "bg-gradient-to-r from-deep-purple-100 to-deep-purple-200 text-deep-purple-500 dark:from-deep-purple-600 dark:to-deep-purple-500 dark:text-deep-purple-50 hover:from-deep-purple-200 hover:to-deep-purple-300 dark:hover:from-deep-purple-500 dark:hover:to-deep-purple-400",
            outline: "border-1 border-deep-purple-500 text-deep-purple-700 dark:text-deep-purple-300 bg-transparent hover:bg-deep-purple-50 dark:hover:bg-deep-purple-900/20",
        },
    },
    blue: {
        primary: {
            from: 'from-blue-500',
            to: 'to-blue-700',
            hoverFrom: 'hover:from-blue-600',
            hoverTo: 'hover:to-blue-800',
        },
        trigger: "border-blue-300 focus:ring-blue-500 focus:border-blue-500",
        icon: "text-blue-500",
        label: "text-blue-800",
        topLine: "from-blue-400 to-blue-600",
        iconBg: "from-blue-100 to-blue-200",
        border: "border-blue-100",
        checked: "data-[state=checked]:bg-blue-600",
        thumb: "data-[state=checked]:bg-blue-100",
        focus: "focus-visible:ring-blue-500",
        active: "bg-gradient-to-r from-blue-500 to-blue-700 text-white shadow-md",
        inactive: "text-blue-600 hover:bg-blue-50 border border-blue-200",
        pills: "text-blue-600 hover:bg-blue-100 data-[state=active]:bg-gradient-to-r data-[state=active]:from-blue-500 data-[state=active]:to-blue-700 data-[state=active]:text-white",
        underline: "border-b-2 border-transparent hover:border-blue-300 data-[state=active]:border-blue-500 text-blue-600",
        cardBorder: "border-blue-200",
        cardSelected: "border-blue-500 bg-blue-50",
        cardText: "text-blue-700",
        cardHover: "hover:border-blue-300",
        title: "text-blue-800",
        hover: "hover:border-blue-300",
        selected: "border-blue-500 bg-blue-50",
        text: "text-blue-700",
        button: {
            primary: "bg-gradient-to-r from-blue-500 to-blue-700 text-white hover:from-blue-600 hover:to-blue-800",
            secondary: "bg-gradient-to-r from-blue-100 to-blue-200 text-blue-500 dark:from-blue-600 dark:to-blue-500 dark:text-blue-50 hover:from-blue-200 hover:to-blue-300 dark:hover:from-blue-500 dark:hover:to-blue-400",
            outline: "border-1 border-blue-500 text-blue-700 dark:text-blue-300 bg-transparent hover:bg-blue-50 dark:hover:bg-blue-900/20",
        },
    },
    orange: {
        primary: {
            from: 'from-orange-500',
            to: 'to-orange-700',
            hoverFrom: 'hover:from-orange-600',
            hoverTo: 'hover:to-orange-800',
        },
        trigger: "border-orange-300 focus:ring-orange-500 focus:border-orange-500",
        icon: "text-orange-500",
        label: "text-orange-800",
        topLine: "from-orange-400 to-orange-600",
        iconBg: "from-orange-100 to-orange-200",
        border: "border-orange-100",
        checked: "data-[state=checked]:bg-orange-600",
        thumb: "data-[state=checked]:bg-orange-100",
        focus: "focus-visible:ring-orange-500",
        active: "bg-gradient-to-r from-orange-500 to-orange-700 text-white shadow-md",
        inactive: "text-orange-600 hover:bg-orange-50 border border-orange-200",
        pills: "text-orange-600 hover:bg-orange-100 data-[state=active]:bg-gradient-to-r data-[state=active]:from-orange-500 data-[state=active]:to-orange-700 data-[state=active]:text-white",
        underline: "border-b-2 border-transparent hover:border-orange-300 data-[state=active]:border-orange-500 text-orange-600",
        cardBorder: "border-orange-200",
        cardSelected: "border-orange-500 bg-orange-50",
        cardText: "text-orange-700",
        cardHover: "hover:border-orange-300",
        title: "text-orange-800",
        hover: "hover:border-orange-300",
        selected: "border-orange-500 bg-orange-50",
        text: "text-orange-700",
        button: {
            primary: "bg-gradient-to-r from-orange-500 to-orange-700 text-white hover:from-orange-600 hover:to-orange-800",
            secondary: "bg-gradient-to-r from-orange-100 to-orange-200 text-orange-500 dark:from-orange-600 dark:to-orange-500 dark:text-orange-50 hover:from-orange-200 hover:to-orange-300 dark:hover:from-orange-500 dark:hover:to-orange-400",
            outline: "border-1 border-orange-500 text-orange-700 dark:text-orange-300 bg-transparent hover:bg-orange-50 dark:hover:bg-orange-900/20",
        },
    },
    teal: {
        primary: {
            from: 'from-teal-500',
            to: 'to-teal-700',
            hoverFrom: 'hover:from-teal-600',
            hoverTo: 'hover:to-teal-800',
        },
        trigger: "border-teal-300 focus:ring-teal-500 focus:border-teal-500",
        icon: "text-teal-500",
        label: "text-teal-800",
        topLine: "from-teal-400 to-teal-600",
        iconBg: "from-teal-100 to-teal-200",
        border: "border-teal-100",
        checked: "data-[state=checked]:bg-teal-600",
        thumb: "data-[state=checked]:bg-teal-100",
        focus: "focus-visible:ring-teal-500",
        active: "bg-gradient-to-r from-teal-500 to-teal-700 text-white shadow-md",
        inactive: "text-teal-600 hover:bg-teal-50 border border-teal-200",
        pills: "text-teal-600 hover:bg-teal-100 data-[state=active]:bg-gradient-to-r data-[state=active]:from-teal-500 data-[state=active]:to-teal-700 data-[state=active]:text-white",
        underline: "border-b-2 border-transparent hover:border-teal-300 data-[state=active]:border-teal-500 text-teal-600",
        cardBorder: "border-teal-200",
        cardSelected: "border-teal-500 bg-teal-50",
        cardText: "text-teal-700",
        cardHover: "hover:border-teal-300",
        title: "text-teal-800",
        hover: "hover:border-teal-300",
        selected: "border-teal-500 bg-teal-50",
        text: "text-teal-700",
        button: {
            primary: "bg-gradient-to-r from-teal-500 to-teal-700 text-white hover:from-teal-600 hover:to-teal-800",
            secondary: "bg-gradient-to-r from-teal-100 to-teal-200 text-teal-500 dark:from-teal-600 dark:to-teal-500 dark:text-teal-50 hover:from-teal-200 hover:to-teal-300 dark:hover:from-teal-500 dark:hover:to-teal-400",
            outline: "border-1 border-teal-500 text-teal-700 dark:text-teal-300 bg-transparent hover:bg-teal-50 dark:hover:bg-teal-900/20",
        },
    },
    yellow: {
        primary: {
            from: 'from-yellow-500',
            to: 'to-yellow-600',
            hoverFrom: 'hover:from-yellow-600',
            hoverTo: 'hover:to-yellow-700',
        },
        trigger: "border-yellow-300 focus:ring-yellow-500 focus:border-yellow-500",
        icon: "text-yellow-500",
        label: "text-yellow-800",
        topLine: "from-yellow-400 to-yellow-600",
        iconBg: "from-yellow-100 to-yellow-200",
        border: "border-yellow-100",
        checked: "data-[state=checked]:bg-yellow-600",
        thumb: "data-[state=checked]:bg-yellow-100",
        focus: "focus-visible:ring-yellow-500",
        active: "bg-gradient-to-r from-yellow-500 to-yellow-600 text-white shadow-md",
        inactive: "text-yellow-600 hover:bg-yellow-50 border border-yellow-200",
        pills: "text-yellow-600 hover:bg-yellow-100 data-[state=active]:bg-gradient-to-r data-[state=active]:from-yellow-500 data-[state=active]:to-yellow-600 data-[state=active]:text-white",
        underline: "border-b-2 border-transparent hover:border-yellow-300 data-[state=active]:border-yellow-500 text-yellow-600",
        cardBorder: "border-yellow-200",
        cardSelected: "border-yellow-500 bg-yellow-50",
        cardText: "text-yellow-700",
        cardHover: "hover:border-yellow-300",
        title: "text-yellow-800",
        hover: "hover:border-yellow-300",
        selected: "border-yellow-500 bg-yellow-50",
        text: "text-yellow-700",
        button: {
            primary: "bg-gradient-to-r from-yellow-500 to-yellow-600 text-white hover:from-yellow-600 hover:to-yellow-700",
            secondary: "bg-gradient-to-r from-yellow-100 to-yellow-200 text-yellow-700 dark:from-yellow-600 dark:to-yellow-500 dark:text-yellow-50 hover:from-yellow-200 hover:to-yellow-300 dark:hover:from-yellow-500 dark:hover:to-yellow-400",
            outline: "border-1 border-yellow-500 text-yellow-700 dark:text-yellow-300 bg-transparent hover:bg-yellow-50 dark:hover:bg-yellow-900/20",
        },
    },
    maroon: {
        primary: {
            from: 'from-rose-600',
            to: 'to-rose-800',
            hoverFrom: 'hover:from-rose-700',
            hoverTo: 'hover:to-rose-900',
        },
        trigger: "border-rose-300 focus:ring-rose-500 focus:border-rose-500",
        icon: "text-rose-500",
        label: "text-rose-800",
        topLine: "from-rose-600 to-rose-800",
        iconBg: "from-rose-100 to-rose-200",
        border: "border-rose-100",
        checked: "data-[state=checked]:bg-rose-700",
        thumb: "data-[state=checked]:bg-rose-100",
        focus: "focus-visible:ring-rose-500",
        active: "bg-gradient-to-r from-rose-600 to-rose-800 text-white shadow-md",
        inactive: "text-rose-600 hover:bg-rose-50 border border-rose-200",
        pills: "text-rose-600 hover:bg-rose-100 data-[state=active]:bg-gradient-to-r data-[state=active]:from-rose-600 data-[state=active]:to-rose-800 data-[state=active]:text-white",
        underline: "border-b-2 border-transparent hover:border-rose-300 data-[state=active]:border-rose-600 text-rose-600",
        cardBorder: "border-rose-200",
        cardSelected: "border-rose-500 bg-rose-50",
        cardText: "text-rose-700",
        cardHover: "hover:border-rose-300",
        title: "text-rose-800",
        hover: "hover:border-rose-300",
        selected: "border-rose-500 bg-rose-50",
        text: "text-rose-700",
        button: {
            primary: "bg-gradient-to-r from-rose-600 to-rose-800 text-white hover:from-rose-700 hover:to-rose-900",
            secondary: "bg-gradient-to-r from-rose-100 to-rose-200 text-rose-600 dark:from-rose-600 dark:to-rose-500 dark:text-rose-50 hover:from-rose-200 hover:to-rose-300 dark:hover:from-rose-500 dark:hover:to-rose-400",
            outline: "border-1 border-rose-600 text-rose-700 dark:text-rose-300 bg-transparent hover:bg-rose-50 dark:hover:bg-rose-900/20",
        },
    },
} as const;

// Default color scheme
export const DEFAULT_COLOR_SCHEME: ColorScheme = 'purple';