/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VisualizationsIndexRouteImport } from './routes/visualizations/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as PracticesIndexRouteImport } from './routes/practices/index'
import { Route as MaterialsIndexRouteImport } from './routes/materials/index'
import { Route as VisualizationsVisualizationTypeRouteImport } from './routes/visualizations/$visualizationType'
import { Route as UsersUserIdRouteImport } from './routes/users/$userId'
import { Route as PracticesPracticeTypeRouteImport } from './routes/practices/$practiceType'
import { Route as MaterialsMaterialTypeRouteImport } from './routes/materials/$materialType'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as PracticesResultPracticeIdRouteImport } from './routes/practices/result/$practiceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisualizationsIndexRoute = VisualizationsIndexRouteImport.update({
  id: '/visualizations/',
  path: '/visualizations/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticesIndexRoute = PracticesIndexRouteImport.update({
  id: '/practices/',
  path: '/practices/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsIndexRoute = MaterialsIndexRouteImport.update({
  id: '/materials/',
  path: '/materials/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisualizationsVisualizationTypeRoute =
  VisualizationsVisualizationTypeRouteImport.update({
    id: '/visualizations/$visualizationType',
    path: '/visualizations/$visualizationType',
    getParentRoute: () => rootRouteImport,
  } as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticesPracticeTypeRoute = PracticesPracticeTypeRouteImport.update({
  id: '/practices/$practiceType',
  path: '/practices/$practiceType',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsMaterialTypeRoute = MaterialsMaterialTypeRouteImport.update({
  id: '/materials/$materialType',
  path: '/materials/$materialType',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticesResultPracticeIdRoute =
  PracticesResultPracticeIdRouteImport.update({
    id: '/practices/result/$practiceId',
    path: '/practices/result/$practiceId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/materials/$materialType': typeof MaterialsMaterialTypeRoute
  '/practices/$practiceType': typeof PracticesPracticeTypeRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/visualizations/$visualizationType': typeof VisualizationsVisualizationTypeRoute
  '/materials': typeof MaterialsIndexRoute
  '/practices': typeof PracticesIndexRoute
  '/users': typeof UsersIndexRoute
  '/visualizations': typeof VisualizationsIndexRoute
  '/practices/result/$practiceId': typeof PracticesResultPracticeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/materials/$materialType': typeof MaterialsMaterialTypeRoute
  '/practices/$practiceType': typeof PracticesPracticeTypeRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/visualizations/$visualizationType': typeof VisualizationsVisualizationTypeRoute
  '/materials': typeof MaterialsIndexRoute
  '/practices': typeof PracticesIndexRoute
  '/users': typeof UsersIndexRoute
  '/visualizations': typeof VisualizationsIndexRoute
  '/practices/result/$practiceId': typeof PracticesResultPracticeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)/login': typeof authLoginRoute
  '/materials/$materialType': typeof MaterialsMaterialTypeRoute
  '/practices/$practiceType': typeof PracticesPracticeTypeRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/visualizations/$visualizationType': typeof VisualizationsVisualizationTypeRoute
  '/materials/': typeof MaterialsIndexRoute
  '/practices/': typeof PracticesIndexRoute
  '/users/': typeof UsersIndexRoute
  '/visualizations/': typeof VisualizationsIndexRoute
  '/practices/result/$practiceId': typeof PracticesResultPracticeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/materials/$materialType'
    | '/practices/$practiceType'
    | '/users/$userId'
    | '/visualizations/$visualizationType'
    | '/materials'
    | '/practices'
    | '/users'
    | '/visualizations'
    | '/practices/result/$practiceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/materials/$materialType'
    | '/practices/$practiceType'
    | '/users/$userId'
    | '/visualizations/$visualizationType'
    | '/materials'
    | '/practices'
    | '/users'
    | '/visualizations'
    | '/practices/result/$practiceId'
  id:
    | '__root__'
    | '/'
    | '/(auth)/login'
    | '/materials/$materialType'
    | '/practices/$practiceType'
    | '/users/$userId'
    | '/visualizations/$visualizationType'
    | '/materials/'
    | '/practices/'
    | '/users/'
    | '/visualizations/'
    | '/practices/result/$practiceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authLoginRoute: typeof authLoginRoute
  MaterialsMaterialTypeRoute: typeof MaterialsMaterialTypeRoute
  PracticesPracticeTypeRoute: typeof PracticesPracticeTypeRoute
  UsersUserIdRoute: typeof UsersUserIdRoute
  VisualizationsVisualizationTypeRoute: typeof VisualizationsVisualizationTypeRoute
  MaterialsIndexRoute: typeof MaterialsIndexRoute
  PracticesIndexRoute: typeof PracticesIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  VisualizationsIndexRoute: typeof VisualizationsIndexRoute
  PracticesResultPracticeIdRoute: typeof PracticesResultPracticeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visualizations/': {
      id: '/visualizations/'
      path: '/visualizations'
      fullPath: '/visualizations'
      preLoaderRoute: typeof VisualizationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practices/': {
      id: '/practices/'
      path: '/practices'
      fullPath: '/practices'
      preLoaderRoute: typeof PracticesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials/': {
      id: '/materials/'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof MaterialsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visualizations/$visualizationType': {
      id: '/visualizations/$visualizationType'
      path: '/visualizations/$visualizationType'
      fullPath: '/visualizations/$visualizationType'
      preLoaderRoute: typeof VisualizationsVisualizationTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practices/$practiceType': {
      id: '/practices/$practiceType'
      path: '/practices/$practiceType'
      fullPath: '/practices/$practiceType'
      preLoaderRoute: typeof PracticesPracticeTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials/$materialType': {
      id: '/materials/$materialType'
      path: '/materials/$materialType'
      fullPath: '/materials/$materialType'
      preLoaderRoute: typeof MaterialsMaterialTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practices/result/$practiceId': {
      id: '/practices/result/$practiceId'
      path: '/practices/result/$practiceId'
      fullPath: '/practices/result/$practiceId'
      preLoaderRoute: typeof PracticesResultPracticeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authLoginRoute: authLoginRoute,
  MaterialsMaterialTypeRoute: MaterialsMaterialTypeRoute,
  PracticesPracticeTypeRoute: PracticesPracticeTypeRoute,
  UsersUserIdRoute: UsersUserIdRoute,
  VisualizationsVisualizationTypeRoute: VisualizationsVisualizationTypeRoute,
  MaterialsIndexRoute: MaterialsIndexRoute,
  PracticesIndexRoute: PracticesIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  VisualizationsIndexRoute: VisualizationsIndexRoute,
  PracticesResultPracticeIdRoute: PracticesResultPracticeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
