/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as PracticesIndexRouteImport } from './routes/practices/index'
import { Route as MaterialsIndexRouteImport } from './routes/materials/index'
import { Route as PracticesPracticeTypeRouteImport } from './routes/practices/$practiceType'
import { Route as MaterialsMaterialTypeRouteImport } from './routes/materials/$materialType'
import { Route as visualization3dvizRouteImport } from './routes/(visualization)/3dviz'
import { Route as visualization2dvizRouteImport } from './routes/(visualization)/2dviz'
import { Route as authLoginRouteImport } from './routes/(auth)/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticesIndexRoute = PracticesIndexRouteImport.update({
  id: '/practices/',
  path: '/practices/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsIndexRoute = MaterialsIndexRouteImport.update({
  id: '/materials/',
  path: '/materials/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticesPracticeTypeRoute = PracticesPracticeTypeRouteImport.update({
  id: '/practices/$practiceType',
  path: '/practices/$practiceType',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsMaterialTypeRoute = MaterialsMaterialTypeRouteImport.update({
  id: '/materials/$materialType',
  path: '/materials/$materialType',
  getParentRoute: () => rootRouteImport,
} as any)
const visualization3dvizRoute = visualization3dvizRouteImport.update({
  id: '/(visualization)/3dviz',
  path: '/3dviz',
  getParentRoute: () => rootRouteImport,
} as any)
const visualization2dvizRoute = visualization2dvizRouteImport.update({
  id: '/(visualization)/2dviz',
  path: '/2dviz',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/2dviz': typeof visualization2dvizRoute
  '/3dviz': typeof visualization3dvizRoute
  '/materials/$materialType': typeof MaterialsMaterialTypeRoute
  '/practices/$practiceType': typeof PracticesPracticeTypeRoute
  '/materials': typeof MaterialsIndexRoute
  '/practices': typeof PracticesIndexRoute
  '/users': typeof UsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/2dviz': typeof visualization2dvizRoute
  '/3dviz': typeof visualization3dvizRoute
  '/materials/$materialType': typeof MaterialsMaterialTypeRoute
  '/practices/$practiceType': typeof PracticesPracticeTypeRoute
  '/materials': typeof MaterialsIndexRoute
  '/practices': typeof PracticesIndexRoute
  '/users': typeof UsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)/login': typeof authLoginRoute
  '/(visualization)/2dviz': typeof visualization2dvizRoute
  '/(visualization)/3dviz': typeof visualization3dvizRoute
  '/materials/$materialType': typeof MaterialsMaterialTypeRoute
  '/practices/$practiceType': typeof PracticesPracticeTypeRoute
  '/materials/': typeof MaterialsIndexRoute
  '/practices/': typeof PracticesIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/2dviz'
    | '/3dviz'
    | '/materials/$materialType'
    | '/practices/$practiceType'
    | '/materials'
    | '/practices'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/2dviz'
    | '/3dviz'
    | '/materials/$materialType'
    | '/practices/$practiceType'
    | '/materials'
    | '/practices'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/(auth)/login'
    | '/(visualization)/2dviz'
    | '/(visualization)/3dviz'
    | '/materials/$materialType'
    | '/practices/$practiceType'
    | '/materials/'
    | '/practices/'
    | '/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authLoginRoute: typeof authLoginRoute
  visualization2dvizRoute: typeof visualization2dvizRoute
  visualization3dvizRoute: typeof visualization3dvizRoute
  MaterialsMaterialTypeRoute: typeof MaterialsMaterialTypeRoute
  PracticesPracticeTypeRoute: typeof PracticesPracticeTypeRoute
  MaterialsIndexRoute: typeof MaterialsIndexRoute
  PracticesIndexRoute: typeof PracticesIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practices/': {
      id: '/practices/'
      path: '/practices'
      fullPath: '/practices'
      preLoaderRoute: typeof PracticesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials/': {
      id: '/materials/'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof MaterialsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practices/$practiceType': {
      id: '/practices/$practiceType'
      path: '/practices/$practiceType'
      fullPath: '/practices/$practiceType'
      preLoaderRoute: typeof PracticesPracticeTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials/$materialType': {
      id: '/materials/$materialType'
      path: '/materials/$materialType'
      fullPath: '/materials/$materialType'
      preLoaderRoute: typeof MaterialsMaterialTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(visualization)/3dviz': {
      id: '/(visualization)/3dviz'
      path: '/3dviz'
      fullPath: '/3dviz'
      preLoaderRoute: typeof visualization3dvizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(visualization)/2dviz': {
      id: '/(visualization)/2dviz'
      path: '/2dviz'
      fullPath: '/2dviz'
      preLoaderRoute: typeof visualization2dvizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authLoginRoute: authLoginRoute,
  visualization2dvizRoute: visualization2dvizRoute,
  visualization3dvizRoute: visualization3dvizRoute,
  MaterialsMaterialTypeRoute: MaterialsMaterialTypeRoute,
  PracticesPracticeTypeRoute: PracticesPracticeTypeRoute,
  MaterialsIndexRoute: MaterialsIndexRoute,
  PracticesIndexRoute: PracticesIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
